"""
Chú thích:
- 'name': Tên của màn chơi.
- 'map_length': Kích thước của bản đồ (ví dụ: 5 cho bản đồ 5x5).
- 'map_data': Mảng 2D mô tả các bức tường.
    + 't': tường trên, 'b': tường dưới, 'l': tường trái, 'r': tường phải
    + 'tl': tường trên-trái, 'tr': tường trên-phải, 'bl': tường dưới-trái, 'br': tường dưới-phải
    + 't*', 'b*', 'l*', 'r*': tường chữ T khuyết
- 'player_start': Vị trí bắt đầu của người chơi [cột, hàng].
- 'stair_position': Vị trí của cầu thang thoát hiểm (cột, hàng).
- 'zombie_starts': Danh sách các vị trí bắt đầu của zombie [[x, y, type], ...].
    + Type 0: Ưu tiên đi phải/trái (horizontal first, dumb)
    + Type 1: Ưu tiên đi lên/xuống (vertical first, dumb)
    + Type 2: Ưu tiên phải/trái, nếu bị chặn thì lên/xuống (horizontal first, smart)
    + Type 3: Ưu tiên lên/xuống, nếu bị chặn thì phải/trái (vertical first, smart)

=== GIAI ĐOẠN 1: TIỀN SẢNH KIM TỰ THÁP (15 màn) ===
Mục tiêu: Làm quen với cơ chế game
Độ khó: Dễ -> Trung bình nhẹ
Quái vật: Chỉ có Xác ướp (1-2 con)
"""

maps_collection = [
    # ==========================================
    # GIAI ĐOẠN 1: TIỀN SẢNH KIM TỰ THÁP
    # Màn 1-15: Làm quen cơ chế, độ khó dễ
    # Kích thước: 6x6 và 8x8
    # ==========================================
    # --- MÀN 1: First Light  ---
    {
        "name": "Generated Map 12x12",
        "map_length": 12,
        "map_data": [
            [""  , ""  , "l" , ""  , ""  , ""  , ""  , "l" , ""  , ""  , ""  , ""  ],
            [""  , ""  , "l" , "t" , "l" , "l" , "tl", ""  , "t" , "tl", ""  , "l" ],
            [""  , "t" , ""  , "t" , "l" , "l" , "l" , "t" , "tl", ""  , "tl", ""  ],
            ["t" , "t" , "tl", ""  , "l" , "l" , "t" , "l" , "l" , "t" , "l" , "t" ],
            [""  , ""  , "l" , "tl", ""  , ""  , "l" , ""  , "tl", ""  , "tl", "l" ],
            [""  , "t" , ""  , "l" , "t" , "tl", "t" , "t" , "l" , "t" , "l" , ""  ],
            [""  , "t" , "t" , "t" , "l" , "l" , "t" , "l" , "tl", ""  , "t" , "l" ],
            [""  , "t" , "l" , "tl", ""  , "l" , "l" , "l" , ""  , "tl", ""  , "l" ],
            ["t" , ""  , "l" , ""  , "t" , "t" , "l" , "l" , ""  , "l" , "t" , "t" ],
            [""  , "tl", "t" , "t" , "t" , "l" , ""  , "l" , "l" , "t" , ""  , "l" ],
            [""  , ""  , "tl", "tl", ""  , "tl", ""  , "tl", ""  , "tl", ""  , "l" ],
            [""  , ""  , ""  , ""  , "t" , ""  , "l" , ""  , "tl", ""  , "t" , ""  ]
        ],
        "player_start": [2, 1],
        "stair_position": [5, 13],
        "zombie_starts": [
            [2, 5, 3],
            [7, 9, 3]
        ],
        "scorpion_starts": [
            [11, 10, 3],
            [10, 6, 3],
            [7, 4, 3]
        ],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000
    },
    {
        "name": "Level 1: map6_11",
        "map_length": 6,
        "map_data": [
            ['', '', '', 'G', '', ''],
            ['', 'l', '', '', 't', ''],
            ['', 'tl', 't', 'tl', '', ''],
            ['', 'l', '', 't', 't', 't'],
            ['', 'K', 't', '', 'r', ''],
            ['', 'T', 't', 't', 'r', ''],
        ],
        "player_start": [1, 1],
        "stair_position": (4, 7),
        "zombie_starts": [[6, 5, 2], [1,6,2], [6,6,0]],
        "scorpion_starts": [[1, 5, 0]],
        "trap_pos": [],
        "key_pos": [2,2],
        "gate_pos": [6,4],
        "level_score": 1000,
    },
    # --- MÀN 2: Tutorial - Né zombie đơn giản ---
    # Mục tiêu: Giới thiệu zombie, học cách né tránh
    {
        
        "name": "Level 2: map6_9",
        "map_length": 6,
        "map_data": [
            ['', 'l', 'l', '', '', ''],
            ['', 'l', 't', 'l', 'l', 't'],
            ['', 'l', 't', '', '', 'l'],
            ['', 't', 't', '', 'l', 'tl'],
            ['', '', 't', '', 'l', ''],
            ['', 't', '', 't', '', ''],
        ],
        "player_start": [3, 3],
        "stair_position": (7, 4),
        "zombie_starts": [[4, 6, 2]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 3: Học cách dùng tường ---
    # Zombie type 0 (vertical first) - bị chặn bởi tường ngang
    {
        "name": "Level 3: map6_2",
        "map_length": 6,
        "map_data": [
            ['', 'l', '', '', '', ''],
            ['', '', '', '', '', ''],
            ['', 'l', '', '', '', ''],
            ['t', '', '', '', '', 't'],
            ['', '', '', '', '', ''],
            ['', '', '', '', '', ''],
        ],
        "player_start": [5, 3],
        "stair_position": (6, 0),
        "zombie_starts": [[2, 4, 2]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 4: Đường vòng ---
    # Zombie type 1 (horizontal first) - bị chặn bởi tường 'l'
    # Player đi về bên trái (không qua cột zombie)
    {
        "name": "Level 4: map6_3",
        "map_length": 6,
        "map_data": [
            ['', 'l', '', '', '', ''],
            ['', '', '', '', '', ''],
            ['', 't', 'l', 't', 'l', ''],
            ['', '', 't', 'tl', 'l', ''],
            ['', 't', 'l', '', 'tl', ''],
            ['', 't', 't', 't', '', ''],
        ],
        "player_start": [5, 2],
        "stair_position": (0, 1),
        "zombie_starts": [[2, 2, 2]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 5: Hai zombie đơn giản ---
    # 2 zombie type 0 (vertical first), bị chặn đi lên bởi tường 't' tại vị trí zombie
    {
        "name": "Level 5: map6_4",
        "map_length": 6,
        "map_data": [
            ['', '', '', '', '', ''],
            ['', 't', '', '', 'l', ''],
            ['', 't', 'l', '', 'l', 't'],
            ['', '', '', 't', '', 'l'],
            ['', '', '', '', '', ''],
            ['', '', '', '', '', ''],
        ],
        "player_start": [4, 2],
        "stair_position": (7, 6),
        "zombie_starts": [[3, 6, 2]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 6: Hành lang hẹp ---
    {
        "name": "Level 6: map6_5",
        "map_length": 6,
        "map_data": [
            ['', '', '', '', '', ''],
            ['', 'l', 't', '', 't', ''],
            ['', '', '', '', 'tl', ''],
            ['t', 'l', 't', '', 't', ''],
            ['', 'l', 'l', 't', '', ''],
            ['', '', 't', 'l', '', ''],
        ],
        "player_start": [3, 3],
        "stair_position": (5, 0),
        "zombie_starts": [[1, 1, 2]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 7: Mê cung chữ L ---
    # Zombie type 1 bị chặn đi trái, player đi về bên trái
    {
        "name": "Level 7: map6_6",
        "map_length": 6,
        "map_data": [
            ['', '', '', '', 'l', ''],
            ['', '', 'l', '', '', ''],
            ['', '', '', 't', '', ''],
            ['', '', '', '', '', ''],
            ['', 'tl', 't', '', '', 't'],
            ['', 'l', '', '', 't', ''],
        ],
        "player_start": [2, 6],
        "stair_position": (2, 0),
        "zombie_starts": [[6, 2, 2]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 8: Smart Hunter ---
    # Smart zombie type 2 bị chặn cả lên và trái bởi 'tl'
    {
        "name": "Level 8: map6_7",
        "map_length": 6,
        "map_data": [
            ['', '', '', '', '', ''],
            ['', '', '', '', '', ''],
            ['', 't', '', 'l', 't', 'T'],
            ['', 'l', 'tl', 't', '', 'l'],
            ['', '', 't', '', '', 't'],
            ['t', '', '', '', '', ''],
        ],
        "player_start": [5, 1],
        "stair_position": (0, 1),
        "zombie_starts": [[3, 6, 2]],
        "scorpion_starts": [[2, 1, 0]],
        "trap_pos": [[3, 6]],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 9: Đường zigzag ---
    {
        "name": "Level 9: map6_8",
        "map_length": 6,
        "map_data": [
            ['', '', '', '', 'l', ''],
            ['b', 'b', '', '', '', 'l'],
            ['', 'b', '', 'tl', 't', ''],
            ['', 'T', '', '', 'l', 'l'],
            ['', '', '', 'l', 't', ''],
            ['', '', '', '', 'l', 'l'],
        ],
        "player_start": [4, 6],
        "stair_position": (0, 5),
        "zombie_starts": [[5, 3, 3]],
        "scorpion_starts": [],
        "trap_pos": [[4, 2]],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 10: Hai zombie khác loại ---
    # Type 0 và type 1 - mỗi loại bị chặn bởi tường khác nhau
    {
        "name": "Level 10: map6_14",
        "map_length": 6,
        "map_data": [
            ['', '', '', 'l', '', ''],
            ['t', '', 'l', 'l', 't', 't'],
            ['t', 'l', 'l', '', '', 'l'],
            ['', '', '', '', 'tl', ''],
            ['', 't', 't', '', 'T', 'l'],
            ['t', '', '', '', 'tl', ''],
        ],
        "player_start": [1, 2],
        "stair_position": (7, 5),
        "zombie_starts": [[6, 6, 2]],
        "scorpion_starts": [],
        "trap_pos": [[5, 5]],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 11: Đường hầm song song ---
    {
        "name": "Level 11: map6_10",
        "map_length": 6,
        "map_data": [
            ['', '', '', '', '', ''],
            ['', '', '', 'tl', 't', ''],
            ['', '', '', 't', '', 'l'],
            ['', '', 'l', '', '', ''],
            ['', '', '', '', '', ''],
            ['', 'l', '', '', '', ''],
        ],
        "player_start": [5, 5],
        "stair_position": (4, 0),
        "zombie_starts": [[2, 4, 2], [2, 5, 2]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 12: Dead Ends - 1 zombie type 0 bị chặn dọc ---
    {
        "name": "Level 12: map6_13",
        "map_length": 6,
        "map_data": [
            ['', '', '', '', '', ''],
            ['', 't', 'l', 't', '', ''],
            ['', 't', 't', 't', '', 'l'],
            ['', 'tl', 'l', '', 't', ''],
            ['', '', 't', '', '', 't'],
            ['', 't', 't', 'tl', 't', ''],
        ],
        "player_start": [2, 2],
        "stair_position": (3, 7),
        "zombie_starts": [[4, 2, 2]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 13: Bao vây - 2 zombie bị chặn ---
    {
        "name": "Level 13: map6_12",
        "map_length": 6,
        "map_data": [
            ['', '', 'l', 'T', '', 'l'],
            ['', '', '', '', 'l', ''],
            ['t', 'K', 't', 't', 'l', 'l'],
            ['t', 't', '', 't', 'l', ''],
            ['t', 'r', 'G', 'tl', '', ''],
            ['', 'tl', '', '', 'l', ''],
        ],
        "player_start": [3, 4],
        "stair_position": (7, 5),
        "zombie_starts": [[1, 6, 2]],
        "scorpion_starts": [[6, 5, 0]],
        "trap_pos": [[1, 4]],
        "key_pos": [3, 2],
        "gate_pos": [5, 3],
        "level_score": 1000,
    },
    # --- MÀN 14: Map 8x8 - 2 zombie type 0 bị chặn dọc ---
    {
        "name": "Level 14: map8_1",
        "map_length": 8,
        "map_data": [
            ['', '', 'l', '', '', '', 'l', ''],
            ['t', 'l', '', '', 'l', 'l', 'l', 't'],
            ['', '', 'tl', '', '', '', 'l', ''],
            ['T', '', '', 't', 'tl', '', '', 'l'],
            ['', 't', 't', '', 'l', 'tl', '', 't'],
            ['t', '', 'l', 'l', 'l', 'tl', '', 't'],
            ['', 't', 'l', '', 'l', 'l', 't', 'l'],
            ['', 'tl', '', '', '', 't', 't', ''],
        ],
        "player_start": [2, 1],
        "stair_position": (7, 9),
        "zombie_starts": [[6, 5, 2], [7, 8, 2]],
        "scorpion_starts": [],
        "trap_pos": [[4, 1]],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 15: BOSS - 2 zombie type 0 bị chặn dọc ---
    {
        "name": "Level 15: map8_7",
        "map_length": 8,
        "map_data": [
            ['', '', '', 'G', 'l', '', '', 'l'],
            ['', '', 'l', 'l', 't', '', 'tl', ''],
            ['', '', 't', 't', '', '', 't', 'l'],
            ['', 't', 'l', '', '', 't', 'l', ''],
            ['', 't', 'l', 'l', 'l', 'l', '', 'K'],
            ['', '', 'l', 'l', 'l', 't', 'l', 'l'],
            ['', 't', 't', '', 't', '', '', ''],
            ['t', '', 'l', '', '', '', 't', ''],
        ],
        "player_start": [1, 2],
        "stair_position": (0, 6),
        "zombie_starts": [[2, 3, 2], [7, 7, 2]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [5, 8],
        "gate_pos": [1, 4],
        "level_score": 1000,
    },
    # ==========================================
    # GIAI ĐOẠN 2: HẦM MỘ TỐI TĂM
    # Màn 16-30: Độ khó trung bình
    # ==========================================
    # --- MÀN 16: Open Field - 2 zombie type 0 bị chặn ---
    {
        "name": "Level 16: map8_8",
        "map_length": 8,
        "map_data": [
            ['', '', 'l', '', '', '', '', 'b'],
            ['', '', '', '', '', '', 'r', 'T'],
            ['', 't', '', '', '', '', 't', ''],
            ['', '', 't', 'l', '', '', '', ''],
            ['t', '', '', '', 'tl', 'l', '', ''],
            ['', '', 'l', 'l', '', 'l', '', ''],
            ['', '', 'l', '', '', 't', '', ''],
            ['', 't', '', 'l', '', 't', '', ''],
        ],
        "player_start": [3, 6],
        "stair_position": (9, 5),
        "zombie_starts": [[5, 6, 2]],
        "scorpion_starts": [],
        "trap_pos": [[2, 8]],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 17: Hai hướng - 1 zombie type 0 bị chặn ---
    {
        "name": "Level 17: Two Ways",
        "map_length": 8,
        "map_data": [
            ["", "r", "l", "", "", "r", "l", ""],
            ["", "", "", "b", "b", "", "", ""],
            ["", "b", "", "t", "t", "", "b", ""],
            ["", "t", "", "b", "b", "", "t", ""],
            ["", "", "", "t", "t", "", "", ""],
            ["", "r", "l", "", "", "r", "l", ""],
            ["", "", "", "b", "b", "", "", ""],
            ["", "", "", "t", "t", "", "", ""],
        ],
        "player_start": [1, 4],
        "stair_position": (9, 4),
        "zombie_starts": [[4, 1, 0]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
    },
    # --- MÀN 18: Center Wall - zombie type 1 bị chặn đi trái ---
    {
        "name": "Level 18: map8_2",
        "map_length": 8,
        "map_data": [
            ['', '', '', '', '', '', '', 'l'],
            ['', 'l', '', 'l', '', '', 't', 'l'],
            ['t', '', '', 't', '', 'l', '', ''],
            ['', 't', '', '', '', '', '', ''],
            ['t', '', 'l', '', '', '', '', ''],
            ['', '', 't', '', '', 't', 'l', ''],
            ['', '', '', '', '', '', '', 'l'],
            ['', 'tl', '', '', '', '', '', ''],
        ],
        "player_start": [5, 6],
        "stair_position": (0, 1),
        "zombie_starts": [[8, 4, 3]],
        "scorpion_starts": [[4, 5, 1]],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 19: Corner Walls - 2 zombie type 0 bị chặn ---
    {
        "name": "Level 19: map8_3",
        "map_length": 8,
        "map_data": [
            ['', '', '', '', '', '', '', ''],
            ['', 'l', '', 't', 't', '', '', ''],
            ['', 'tr', 'K', '', 'l', '', 'l', ''],
            ['', '', '', '', '', 'l', '', 'tl'],
            ['', '', '', '', '', '', 'l', ''],
            ['', '', 'G', '', 'l', '', '', 'l'],
            ['t', '', '', '', '', '', '', 'l'],
            ['', '', '', '', '', '', 'l', ''],
        ],
        "player_start": [3, 7],
        "stair_position": (9, 8),
        "zombie_starts": [[8, 4, 2]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [3, 3],
        "gate_pos": [6, 3],
        "level_score": 1000,
    },
    # --- MÀN 20: Wide Arena - zombie type 0 bị chặn dọc ---
    {
        "name": "Level 20: map8_4",
        "map_length": 8,
        "map_data": [
            ['', '', '', '', '', '', '', 'l'],
            ['', '', '', '', '', '', '', ''],
            ['', '', 'r', 'K', '', '', '', ''],
            ['', 'l', '', '', 'l', 't', 't', 't'],
            ['', 'tl', 'G', '', '', '', 'l', ''],
            ['', '', '', 'l', 't', 'l', '', ''],
            ['', '', '', '', 't', 't', '', 't'],
            ['T', 'l', 't', 'l', '', '', '', ''],
        ],
        "player_start": [2, 4],
        "stair_position": (2, 9),
        "zombie_starts": [[7, 6, 2]],
        "scorpion_starts": [[8, 2, 0]],
        "trap_pos": [[8, 1]],
        "key_pos": [[3, 4]],
        "gate_pos": [5, 3],
        "level_score": 1000,
    },
    # --- MÀN 21: Triple Threat - 3 zombie type 0 bị chặn ---
    {
        "name": "Level 21: map8_5",
        "map_length": 8,
        "map_data": [
            ['', '', '', '', '', '', '', ''],
            ['', '', 'l', 't', '', 'l', 'l', ''],
            ['t', '', '', 'l', 'l', 'l', '', ''],
            ['', 'tl', '', '', '', '', '', ''],
            ['', '', 'l', 'l', 't', 't', 'b', ''],
            ['', '', 't', '', 't', 'l', 'T', 'l'],
            ['', 't', '', 'tl', '', 'tl', '', ''],
            ['', 't', '', 'l', 'l', '', 'l', 't'],
        ],
        "player_start": [8, 1],
        "stair_position": (6, 9),
        "zombie_starts": [[1, 5, 3], [7, 5, 3]],
        "scorpion_starts": [],
        "trap_pos": [[6, 7]],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 22: Straight Path - zombie type 0 bị chặn dọc ---
    {
        "name": "Level 22: map8_6",
        "map_length": 8,
        "map_data": [
            ['', '', '', 'l', 'l', '', 'l', ''],
            ['', '', 'tl', '', 'tl', '', 'l', ''],
            ['', '', 'l', '', 't', '', 'l', ''],
            ['', '', '', 't', '', 't', '', 't'],
            ['t', '', '', '', 'l', 't', 'l', 't'],
            ['', '', 'l', '', 'l', 'tl', '', 't'],
            ['', 'l', 't', '', 't', 'tl', 'T', ''],
            ['t', '', '', 'l', 't', '', '', ''],
        ],
        "player_start": [2, 4],
        "stair_position": (0, 1),
        "zombie_starts": [[3, 1, 0]],
        "scorpion_starts": [[8, 6, 0]],
        "trap_pos": [[7, 7]],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 23: H Shape - 2 zombie type 1 bị chặn ---
    {
        "name": "Level 23: H Shape",
        "map_length": 8,
        "map_data": [
            ["", "b", "", "r", "l", "", "b", ""],
            ["", "t", "r", "", "", "l", "t", ""],
            ["", "", "r", "b", "b", "l", "", ""],
            ["", "", "", "t", "t", "", "", ""],
            ["", "r", "l", "", "", "r", "l", ""],
            ["", "", "r", "", "", "l", "", ""],
            ["", "b", "", "t", "t", "l", "b", ""],
            ["", "t", "", "", "", "", "t", ""],
        ],
        "player_start": [1, 4],
        "stair_position": (9, 4),
        "zombie_starts": [[4, 1, 1], [4, 8, 1]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 24: Four Corners - 2 zombie type 0 bị chặn ---
    {
        "name": "Level 24: Four Corners",
        "map_length": 8,
        "map_data": [
            ["", "r", "", "r", "", "r", "", ""],
            ["", "", "", "t", "", "", "b", ""],
            ["", "b", "", "", "b", "r", "l", ""],
            ["", "t", "r", "l", "", "", "t", ""],
            ["", "", "", "b", "", "b", "", ""],
            ["", "r", "l", "", "", "r", "l", ""],
            ["", "", "", "b", "", "", "", ""],
            ["", "r", "l", "t", "t", "r", "l", ""],
        ],
        "player_start": [5, 4],
        "stair_position": (5, 0),
        "zombie_starts": [[2, 2, 0], [7, 7, 0]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 25: Mini Boss - 2 zombie type 0 bị chặn ---
    {
        "name": "Level 25: Mini Boss",
        "map_length": 8,
        "map_data": [
            ["", "b", "", "r", "l", "", "b", ""],
            ["", "t", "r", "", "", "l", "t", ""],
            ["", "", "", "b", "b", "", "", ""],
            ["", "r", "l", "t", "t", "r", "l", ""],
            ["", "", "", "", "", "", "", ""],
            ["", "b", "r", "", "", "l", "b", ""],
            ["", "t", "", "r", "l", "", "t", ""],  # Chặn zombie
            ["", "", "", "", "", "", "", ""],
        ],
        "player_start": [1, 4],
        "stair_position": (9, 4),
        "zombie_starts": [[2, 7, 0], [7, 7, 0]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 26: Big Arena 10x10 - 2 zombie type 0 bị chặn ---
    {
        "name": "Level 26: map10_3",
        "map_length": 10,
        "map_data": [
            ['', 'l', '', '', '', 'l', '', '', '', 'l'],
            ['', '', '', 't', '', 't', '', '', '', ''],
            ['', 'tl', '', '', '', 't', 't', 't', 'l', 't'],
            ['', '', '', '', 't', '', 't', '', 'l', 't'],
            ['', '', '', '', '', '', '', 't', 'l', ''],
            ['', 't', 't', '', '', '', 'T', 'l', 't', ''],
            ['', '', 'l', 't', 'l', 'l', '', '', '', ''],
            ['', '', '', 'l', 'l', '', 'l', '', 'l', 't'],
            ['', 't', 'l', 'l', '', '', '', '', 'l', 't'],
            ['', 'l', '', '', 't', '', '', '', '', 't'],
        ],
        "player_start": [10, 10],
        "stair_position": (0, 1),
        "zombie_starts": [[2, 4, 3]],
        "scorpion_starts": [[9, 6, 1]],
        "trap_pos": [[6, 7]],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 27: Many Walls - 2 zombie type 1 bị chặn ---
    {
        "name": "Level 27: map10_4",
        "map_length": 10,
        "map_data": [
            ['', '', '', '', '', '', 'l', '', '', 'l'],
            ['', 'l', '', 'tl', 'l', '', '', '', '', ''],
            ['T', 't', '', 'l', 't', 't', 't', '', '', ''],
            ['', 'l', '', '', '', 'tl', '', 'l', 'l', 't'],
            ['t', 't', 'l', 't', '', 't', 't', '', 'l', ''],
            ['t', '', 't', 't', 'l', 'l', '', '', '', ''],
            ['', 'l', 't', 'l', 't', '', 'G', '', 't', 'l'],
            ['', 't', '', 'tl', '', 'tl', '', 't', 't', 'l'],
            ['', 't', 'l', 'tr', 'K', 'l', '', 'l', '', 't'],
            ['', 't', 'l', '', 'l', '', '', 't', 't', 't'],
        ],
        "player_start": [6, 7],
        "stair_position": (11, 7),
        "zombie_starts": [[5, 10, 2]],
        "scorpion_starts": [],
        "trap_pos": [[3, 1]],
        "key_pos": [[9, 5]],
        "gate_pos": [7, 7],
        "level_score": 1000,
    },
    # --- MÀN 28: Large Room - 2 zombie type 0 bị chặn ---
    {
        "name": "Level 28: map10_5",
        "map_length": 10,
        "map_data": [
            ['', 'l', '', '', 'l', '', '', '', '', 'l'],
            ['', 'l', '', 'l', 'tl', 't', '', 'l', '', ''],
            ['', 'tl', 'l', '', 't', '', '', '', 'tl', ''],
            ['', '', '', '', '', '', '', 't', 't', ''],
            ['', 't', 't', 'l', '', 'l', '', '', 't', ''],
            ['', '', '', 'l', 'tl', '', 'l', 't', 'l', ''],
            ['', '', '', 'l', '', 'tl', 'r', 'T', '', 'tl'],
            ['', 'l', '', '', 't', '', 'l', '', 't', ''],
            ['t', '', 't', 'tl', '', '', '', '', '', ''],
            ['t', '', '', '', '', '', '', '', 'l', 't'],
        ],
        "player_start": [3, 4],
        "stair_position": (0, 1),
        "zombie_starts": [[5, 8, 3], [9, 2, 3]],
        "scorpion_starts": [],
        "trap_pos": [[7, 8]],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 29: Corner Blocks - 3 zombie type 0 bị chặn ---
    {
        "name": "Level 29: map10_1",
        "map_length": 10,
        "map_data": [
            ['', '', '', 'l', '', 'l', '', '', '', ''],
            ['t', '', '', 'l', '', 'tl', 't', 't', 't', ''],
            ['', 'l', 'l', '', 'l', '', 'l', '', 'l', ''],
            ['', 't', '', '', '', '', '', '', 'r', 'K'],
            ['', '', 'l', 'l', '', 't', 't', 'l', 't', 't'],
            ['', 'tl', 't', 't', 't', '', 't', '', '', ''],
            ['', '', '', 'T', 'l', '', '', '', 't', ''],
            ['', 'l', 't', 'l', 't', '', '', '', '', 't'],
            ['t', '', 't', '', 'G', 't', '', 'tl', 'l', ''],
            ['', '', 't', 'l', 't', 't', 'l', '', '', 't'],
        ],
        "player_start": [7, 8],
        "stair_position": (10, 0),
        "zombie_starts": [[1, 10, 2], [9, 3, 2]],
        "scorpion_starts": [[9, 10, 0]],
        "trap_pos": [[7, 4]],
        "key_pos": [[4, 10]],
        "gate_pos": [9, 5],
        "level_score": 1000,
    },
    # --- MÀN 30: BOSS - 2 zombie type 0 bị chặn ---
    {
        "name": "Level 2: map10_2",
        "map_length": 10,
        "map_data": [
            ['', 'l', '', '', 'l', '', '', '', '', 'l'],
            ['', 'l', '', 'l', 'tl', 't', '', 'l', '', ''],
            ['', 'tl', '', '', 't', '', '', '', 'tl', ''],
            ['', '', '', '', '', '', '', 't', 't', ''],
            ['', 't', 't', 'l', '', 'l', '', '', 't', ''],
            ['', '', '', 'l', 'tl', '', 'l', 't', 'l', ''],
            ['', '', '', 'l', '', 'tl', '', 'T', '', 'tl'],
            ['', 'l', '', '', 't', '', 'l', '', 't', ''],
            ['t', '', 't', 'tl', 'l', 'l', '', '', '', ''],
            ['t', '', '', '', 't', '', '', '', 'l', 't'],
        ],
        "player_start": [3, 4],
        "stair_position": (0, 1),
        "zombie_starts": [[5, 8, 3], [9, 2, 3]],
        "scorpion_starts": [],
        "trap_pos": [[7, 8]],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # ==========================================
    # GIAI ĐOẠN 3: ĐIỆN THỜ HOÀNG GIA
    # Màn 31-45: Độ khó cao
    # ==========================================
    # --- MÀN 31: Royal Arena - 3 zombie bị chặn ---
    {
        "name": "Level 31: Royal Arena",
        "map_length": 10,
        "map_data": [
            ["", "", "r", "", "", "", "l", "", "", ""],
            ["", "", "b", "", "", "", "", "b", "", ""],
            ["", "", "t", "", "r", "l", "", "t", "", ""],
            ["", "r", "", "", "", "", "", "", "l", ""],
            ["", "", "", "", "b", "b", "", "", "", ""],
            ["", "", "r", "", "t", "t", "", "l", "", ""],
            ["", "", "", "", "", "", "", "", "", ""],
            ["", "b", "", "r", "", "", "l", "", "b", ""],
            ["", "t", "", "", "", "", "", "", "t", ""],
            ["", "", "", "r", "", "", "l", "", "", ""],
        ],
        "player_start": [1, 10],
        "stair_position": (11, 1),
        "zombie_starts": [[4, 3, 0], [7, 8, 1]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 32: Wall Maze - Asymmetric maze with 2 zombies ---
    {
        "name": "Level 32: Wall Maze",
        "map_length": 10,
        "map_data": [
            ["", "", "", "", "", "", "", "", "", ""],
            ["", "b", "", "", "", "", "", "b", "", ""],
            ["", "t", "", "", "r", "", "", "t", "", ""],
            ["", "", "", "b", "", "", "", "", "", ""],
            ["", "r", "", "t", "", "", "b", "", "", ""],
            ["", "", "", "", "", "", "t", "", "", ""],
            ["", "", "b", "", "", "", "", "", "l", ""],
            ["", "", "t", "", "", "b", "", "", "", ""],
            ["", "", "", "", "", "t", "", "r", "", ""],
            ["", "", "", "r", "", "", "", "", "", ""],
        ],
        "player_start": [5, 5],
        "stair_position": (6, 0),
        "zombie_starts": [[1, 8, 0], [8, 1, 1]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 33: Twisted Path - Winding corridors ---
    {
        "name": "Level 33: Twisted Path",
        "map_length": 10,
        "map_data": [
            ["", "", "", "b", "", "", "", "", "", ""],
            ["", "r", "", "t", "", "", "", "", "l", ""],
            ["", "", "", "", "", "r", "", "", "", ""],
            ["", "b", "", "", "", "", "", "b", "", ""],
            ["", "t", "", "", "", "b", "", "t", "", ""],
            ["", "", "", "", "", "t", "", "", "", ""],
            ["", "", "r", "", "", "", "", "", "l", ""],
            ["", "b", "", "", "", "", "", "", "", ""],
            ["", "t", "", "", "", "", "", "", "r", ""],
            ["", "", "", "r", "", "", "", "", "", ""],
        ],
        "player_start": [1, 5],
        "stair_position": (11, 5),
        "zombie_starts": [[4, 8, 0], [8, 3, 1]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 34: Grand Hall 12x12 - Complex asymmetric layout ---
    {
        "name": "Level 34: Grand Hall",
        "map_length": 12,
        "map_data": [
            ["", "", "", "r", "", "", "", "", "b", "", "", ""],
            ["", "b", "", "", "", "", "", "", "t", "", "l", ""],
            ["", "t", "", "", "", "r", "", "", "", "", "", ""],
            ["", "", "", "b", "", "", "", "", "", "", "", ""],
            ["", "r", "", "t", "", "", "", "", "", "", "b", ""],
            ["", "", "", "", "", "", "b", "", "l", "", "t", ""],
            ["", "", "b", "", "", "", "t", "", "", "", "", ""],
            ["", "", "t", "", "", "", "", "r", "", "", "", ""],
            ["", "", "", "", "", "b", "", "", "", "b", "", ""],
            ["", "b", "", "", "", "t", "", "", "", "t", "", ""],
            ["", "t", "", "r", "", "", "", "", "", "", "l", ""],
            ["", "", "", "", "", "", "r", "", "", "", "", ""],
        ],
        "player_start": [6, 6],
        "stair_position": (7, 0),
        "zombie_starts": [[3, 3, 0], [9, 9, 1]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 35: Serpent Path 12x12 - Snake-like corridors ---
    {
        "name": "Level 35: Serpent Path",
        "map_length": 12,
        "map_data": [
            ["", "", "", "", "r", "", "", "", "", "b", "", ""],
            ["", "b", "", "", "", "", "b", "", "", "t", "", ""],
            ["", "t", "", "r", "", "", "t", "", "", "", "l", ""],
            ["", "", "", "", "", "", "", "", "b", "", "", ""],
            ["", "", "b", "", "", "r", "", "", "t", "", "", ""],
            ["", "", "t", "", "", "", "", "", "", "", "r", ""],
            ["", "r", "", "", "b", "", "", "l", "", "", "", ""],
            ["", "", "", "", "t", "", "", "", "", "b", "", ""],
            ["", "", "", "", "", "", "r", "", "", "t", "", ""],
            ["", "b", "", "", "", "", "", "", "", "", "l", ""],
            ["", "t", "", "r", "", "b", "", "", "", "", "", ""],
            ["", "", "", "", "", "t", "", "r", "", "", "", ""],
        ],
        "player_start": [3, 6],
        "stair_position": (0, 6),
        "zombie_starts": [[9, 3, 1], [5, 9, 0], [7, 5, 0]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 36: Labyrinth 12x12 - Complex maze pattern ---
    {
        "name": "Level 36: Labyrinth",
        "map_length": 12,
        "map_data": [
            ["", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "b", "", "", "", "", "", "", "", "", "", ""],
            ["", "t", "", "", "", "", "", "r", "", "", "", ""],
            ["", "", "", "b", "", "", "", "r", "", "", "", ""],
            ["", "r", "", "t", "", "", "", "", "", "b", "", ""],
            ["", "", "", "", "", "", "", "", "", "t", "", ""],
            ["", "", "b", "", "", "", "", "", "", "", "", ""],
            ["", "", "t", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "b", "", "", ""],
            ["", "b", "", "", "", "", "", "", "t", "", "", ""],
            ["", "t", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", ""],
        ],
        "player_start": [6, 6],
        "stair_position": (7, 0),
        "zombie_starts": [[3, 10, 0], [10, 3, 1]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 37: Dragon's Path 12x12 - Winding corridors ---
    {
        "name": "Level 37: Dragon's Path",
        "map_length": 12,
        "map_data": [
            ["", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "b", "", "", "", "r", "", "", "", "b", "", ""],
            ["", "t", "", "r", "", "", "", "", "", "t", "", ""],
            ["", "", "", "", "", "", "b", "", "", "", "", ""],
            ["", "", "b", "", "", "", "t", "", "r", "", "", ""],
            ["", "", "t", "", "", "", "", "", "", "", "", ""],
            ["", "r", "", "", "", "", "", "", "", "b", "", ""],
            ["", "", "", "", "b", "", "", "", "", "t", "", ""],
            ["", "", "", "", "t", "", "", "r", "", "", "", ""],
            ["", "", "r", "", "", "", "", "", "", "", "l", ""],
            ["", "b", "", "", "", "", "b", "", "", "", "", ""],
            ["", "t", "", "", "", "", "t", "", "", "", "", ""],
        ],
        "player_start": [10, 10],
        "stair_position": (0, 1),
        "zombie_starts": [[3, 3, 0], [8, 6, 1]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 38: Crossroads 12x12 - Multiple pathways ---
    {
        "name": "Level 38: Crossroads",
        "map_length": 12,
        "map_data": [
            ["", "", "", "", "r", "", "", "", "", "b", "", ""],
            ["", "b", "", "", "", "", "b", "", "", "t", "", ""],
            ["", "t", "", "r", "", "", "t", "", "", "", "l", ""],
            ["", "", "", "r", "", "", "", "", "b", "", "", ""],
            ["", "", "b", "", "", "r", "", "", "t", "", "", ""],
            ["", "", "t", "", "", "", "", "", "", "", "r", ""],
            ["", "r", "", "", "b", "", "", "l", "", "", "", ""],
            ["", "", "", "", "t", "", "", "", "", "b", "", ""],
            ["", "", "", "", "", "", "r", "", "", "t", "", ""],
            ["", "b", "", "", "", "", "", "", "", "", "l", ""],
            ["", "t", "", "r", "", "b", "", "", "", "", "", ""],
            ["", "", "", "", "", "t", "", "r", "", "", "", ""],
        ],
        "player_start": [6, 6],
        "stair_position": (7, 0),
        "zombie_starts": [[3, 4, 0], [9, 8, 1]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 39: Shadow Maze 12x12 - Dark corridors ---
    {
        "name": "Level 39: Shadow Maze",
        "map_length": 12,
        "map_data": [
            ["", "", "r", "", "", "", "", "", "b", "", "", ""],
            ["", "b", "", "", "", "r", "", "", "t", "", "l", ""],
            ["", "t", "", "b", "", "", "", "", "", "", "", ""],
            ["", "", "", "t", "", "", "b", "", "r", "", "", ""],
            ["", "r", "", "", "", "", "t", "", "", "", "b", ""],
            ["", "", "", "", "r", "", "", "", "l", "", "t", ""],
            ["", "", "b", "", "", "", "", "", "", "", "", ""],
            ["", "", "t", "", "", "b", "", "r", "", "", "", ""],
            ["", "", "", "", "", "t", "", "", "", "b", "", ""],
            ["", "b", "", "r", "", "", "", "", "", "t", "", ""],
            ["", "t", "", "", "", "", "r", "", "", "", "l", ""],
            ["", "", "", "", "r", "", "", "", "", "", "", ""],
        ],
        "player_start": [5, 6],
        "stair_position": (0, 6),
        "zombie_starts": [[3, 10, 1], [9, 3, 0]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 40: Arena of Trials 12x12 - Challenge arena ---
    {
        "name": "Level 40: Arena of Trials",
        "map_length": 12,
        "map_data": [
            ["", "", "", "", "", "", "", "", "b", "", "", ""],
            ["", "b", "", "", "", "", "r", "", "t", "", "", ""],
            ["", "t", "", "", "", "", "", "", "", "", "l", ""],
            ["", "", "", "b", "", "", "", "", "", "", "", ""],
            ["", "", "", "t", "", "r", "", "", "", "", "b", ""],
            ["", "r", "", "", "", "", "", "", "", "", "t", ""],
            ["", "", "", "", "b", "", "", "", "", "", "", ""],
            ["", "", "b", "", "t", "", "", "", "", "", "", ""],
            ["", "", "t", "", "", "", "", "", "", "b", "", ""],
            ["", "", "", "", "r", "", "", "", "", "t", "l", ""],
            ["", "b", "", "", "", "", "", "", "", "", "", ""],
            ["", "t", "", "r", "", "", "", "", "r", "", "", ""],
        ],
        "player_start": [1, 6],
        "stair_position": (13, 6),
        "zombie_starts": [[4, 4, 0], [9, 9, 1]],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 41: Imperial Palace 16x16 - Massive asymmetric maze ---
    {
        "name": "Level 41: Imperial Palace",
        "map_length": 16,
        "map_data": [
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        ],
        "player_start": [],
        "stair_position": (),
        "zombie_starts": [],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 42: Cursed Catacombs 16x16 - Winding underground ---
    {
        "name": "Level 42: Cursed Catacombs",
        "map_length": 16,
        "map_data": [
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        ],
        "player_start": [],
        "stair_position": (),
        "zombie_starts": [],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 43: Pharaoh's Passage 16x16 - Royal corridors ---
    {
        "name": "Level 43: Pharaoh's Passage",
        "map_length": 16,
        "map_data": [
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        ],
        "player_start": [],
        "stair_position": (),
        "zombie_starts": [],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 44: Throne's Approach 16x16 - Final approach ---
    {
        "name": "Level 44: Throne's Approach",
        "map_length": 16,
        "map_data": [
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        ],
        "player_start": [],
        "stair_position": (),
        "zombie_starts": [],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
    # --- MÀN 45: FINAL BOSS 16x16 - Ultimate challenge ---
    {
        "name": "Level 45: Final Boss",
        "map_length": 16,
        "map_data": [
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
            ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        ],
        "player_start": [],
        "stair_position": (),
        "zombie_starts": [],
        "scorpion_starts": [],
        "trap_pos": [],
        "key_pos": [],
        "gate_pos": [],
        "level_score": 1000,
    },
]
